const QUESTIONS = [
  'When did guitar music first become prevalent?',
  `Where did guitars first appear?`,
  `Strings and frets were originally made out of ________?`,
  `The first electric guitar dates back to ____?`,
  `The ___________ was the first successful, mass-produced solid body electric guitar.`,
  `Where was the world's biggest playable electric guitar built?`,
  `Where was the world's largest playable acoustic guitar built?`,
  `Kurt Cobain's guitar from Nirvana's 1993 MTV Unplugged performance sold for how much?`,
  `Who is the most influential guitarist of all time?`,
  `The Fender factory makes how many strings each day?`,
];
const ANSWERS = [
  `The 1800's`,
  `Spain`,
  `Animal Guts`,
  `1931`,
  `Fender Telecaster`,
  `Conroe, Texas`,
  `Porto, Portugal`,
  `$6.01 Million`,
  `Jimi Hendrix`,
  `90,000`,
];
const questionOptions = {
  answer1: [
    `The 1700's`,
    `Spain`,
    `Wood`,
    `1931`,
    `Gibson Les Paul`,
    `New York City, New York`,
    `Austin, Texas`,
    `$6.01 Million`,
    `Lindsay Buckingham`,
    `90,000`,
  ],
  answer2: [
    `The 1800's`,
    `America`,
    `Metal`,
    `1981`,
    `Fender Telecaster`,
    `San Francisco, California`,
    `San Jose, Costa Rica`,
    `$10.9 Million`,
    `Jimi Hendrix`,
    `150,000`,
  ],
  answer3: [
    `The 1900's`,
    `Germany`,
    `Animal Guts`,
    `1952`,
    `Fender Stratocaster`,
    `Conroe, Texas`,
    `Madrid, Spain`,
    `$565,000`,
    `Eric Clapton`,
    `10,000`,
  ],
  answer4: [
    `The 2000's`,
    `France`,
    `Leather`,
    `1893`,
    `Gibson ES-335`,
    `Lincoln, Nebraska`,
    `Porto, Portugal`,
    `$915,000`,
    `Jimmy Page`,
    `25,000`,
  ],
};
